<a href="https://www.kaggle.com/code/luckysingh3003/rnn-sentiment-analysis?scriptVersionId=305176447" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## RNN Implementation

In [2]:
import numpy as np
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
from keras import Sequential

In [3]:
 # list
doc = [
    
        'I love this movie',
        'This is terrible',
        'Amazing experience',
        'Worst film ever',
        'Very good acting',
        'Not good at all'
    ]
labels = [1, 0, 1, 0, 1, 0]   # sentiment labels

In [4]:
# A Tokenizer converts text (words) into numbers (tokens)
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>')

In [5]:
tokenizer.fit_on_texts(doc)

In [6]:
tokenizer.word_index

{'<nothing>': 1,
 'this': 2,
 'good': 3,
 'i': 4,
 'love': 5,
 'movie': 6,
 'is': 7,
 'terrible': 8,
 'amazing': 9,
 'experience': 10,
 'worst': 11,
 'film': 12,
 'ever': 13,
 'very': 14,
 'acting': 15,
 'not': 16,
 'at': 17,
 'all': 18}

In [8]:
tokenizer.word_counts

OrderedDict([('i', 1),
             ('love', 1),
             ('this', 2),
             ('movie', 1),
             ('is', 1),
             ('terrible', 1),
             ('amazing', 1),
             ('experience', 1),
             ('worst', 1),
             ('film', 1),
             ('ever', 1),
             ('very', 1),
             ('good', 2),
             ('acting', 1),
             ('not', 1),
             ('at', 1),
             ('all', 1)])

In [9]:
tokenizer.document_count

6

In [6]:
sequence = tokenizer.texts_to_sequences(doc)
sequence

[[4, 5, 2, 6], [2, 7, 8], [9, 10], [11, 12, 13], [14, 3, 15], [16, 3, 17, 18]]

In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = pad_sequences(sequence, padding='post') 

In [8]:
sequences

array([[ 4,  5,  2,  6],
       [ 2,  7,  8,  0],
       [ 9, 10,  0,  0],
       [11, 12, 13,  0],
       [14,  3, 15,  0],
       [16,  3, 17, 18]], dtype=int32)

In [12]:
vocab_size = len(tokenizer.word_index) + 1

In [14]:
from keras.layers import Input
max_len = 5   # example
model = Sequential()
model.add(Input(shape=(max_len,)))   

model.add(Embedding(vocab_size, output_dim=2))
model.add(SimpleRNN(16))    
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 5, 2)           │            38 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 16)             │           304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 359 (1.40 KB)

 Trainable params: 359 (1.40 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [16]:
model.fit(sequences, np.array(labels), epochs=20,validation_split=0.2)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.7500 - loss: 0.6843 - val_accuracy: 0.5000 - val_loss: 0.7086
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.6822 - val_accuracy: 0.5000 - val_loss: 0.7092
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.6800 - val_accuracy: 0.5000 - val_loss: 0.7096
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.6778 - val_accuracy: 0.5000 - val_loss: 0.7100
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 1.0000 - loss: 0.6756 - val_accuracy: 0.5000 - val_loss: 0.7104
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 1.0000 - loss: 0.6732 - val_accuracy: 0.5000 - val_loss: 0.7108
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 1.0000 - loss: 0.6707 - val_accuracy: 0.5000 - val_loss: 0.7112
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 1.0000 - loss: 0.6682 - val_accuracy: 0.5000 - val_loss: 0.7116
Ep

#### data is so small

In [93]:
test = ['I love this', 'This is bad']

test_seq = tokenizer.texts_to_sequences(test)
test_pad = pad_sequences(test_seq, maxlen=max_len, padding='post')

pred = model.predict(test_pad)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
[[0.59385043]
 [0.41318777]]


In [17]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [37]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [38]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [39]:
X_train.shape

(25000,)

In [49]:
X_train=pad_sequences(X_train,padding='post')
X_test=pad_sequences(X_test,padding='post')

In [50]:
X_train.shape

(25000, 100)

In [51]:
# first review
X_train[0]

array([ 1415,    33,     6,    22,    12,   215,    28,    77,    52,
           5,    14,   407,    16,    82, 10311,     8,     4,   107,
         117,  5952,    15,   256,     4, 31050,     7,  3766,     5,
         723,    36,    71,    43,   530,   476,    26,   400,   317,
          46,     7,     4, 12118,  1029,    13,   104,    88,     4,
         381,    15,   297,    98,    32,  2071,    56,    26,   141,
           6,   194,  7486,    18,     4,   226,    22,    21,   134,
         476,    26,   480,     5,   144,    30,  5535,    18,    51,
          36,    28,   224,    92,    25,   104,     4,   226,    65,
          16,    38,  1334,    88,    12,    16,   283,     5,    16,
        4472,   113,   103,    32,    15,    16,  5345,    19,   178,
          32], dtype=int32)

In [106]:
model = Sequential()

model.add(Embedding(np.max(X_train)+1, 2, input_length=X_train.shape[1]))  

model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

In [107]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [108]:
model.fit(X_train,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 25s 29ms/step - accuracy: 0.5337 - loss: 0.6828 - val_accuracy: 0.7925 - val_loss: 0.4584
Epoch 2/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.8209 - loss: 0.4137 - val_accuracy: 0.8241 - val_loss: 0.4095
Epoch 3/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.8991 - loss: 0.2680 - val_accuracy: 0.8090 - val_loss: 0.4574
Epoch 4/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.9303 - loss: 0.1968 - val_accuracy: 0.8335 - val_loss: 0.4617
Epoch 5/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 22s 29ms/step - accuracy: 0.9421 - loss: 0.1699 - val_accuracy: 0.8263 - val_loss: 0.4599
Epoch 6/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.9576 - loss: 0.1294 - val_accuracy: 0.8261 - val_loss: 0.5021
Epoch 7/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.9660 - loss: 0.1094 - val_accuracy: 0.8186 - val_loss: 0.5110
Epoch 8/20
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.9615 - loss: 0.1138 - 